/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CardHomeView: typeof import('./src/components/HomeView/CardHomeView.vue')['default']
    CarouselHomeView: typeof import('./src/components/HomeView/CarouselHomeView.vue')['default']
    ColorWatcher: typeof import('./src/components/Global/ColorWatcher.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Drawer: typeof import('primevue/drawer')['default']
    GridItemsSideBar: typeof import('./src/components/SideBar/GridItemsSideBar.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MenuNavigationSideBar: typeof import('./src/components/SideBar/MenuNavigationSideBar.vue')['default']
    RootSideBar: typeof import('./src/components/SideBar/RootSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SettingsSideBar: typeof import('./src/components/SideBar/SettingsSideBar.vue')['default']
    SocialViewDatatable: typeof import('./src/components/SocialView/SocialViewDatatable.vue')['default']
    SupabaseAccount: typeof import('./src/components/Supabase/supabaseAccount.vue')['default']
    SupabaseAuth: typeof import('./src/components/Supabase/supabaseAuth.vue')['default']
    SupabaseLogin: typeof import('./src/components/Global/supabaseLogin.vue')['default']
    SVGWavesHeader: typeof import('./src/components/Header/SVGWavesHeader.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    WavesHeader: typeof import('./src/components/Header/WavesHeader.vue')['default']
    WelcomeHeader: typeof import('./src/components/Header/WelcomeHeader.vue')['default']
  }
  export interface GlobalDirectives {
    FocusTrap: typeof import('primevue/focustrap')['default']
  }
}
