/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ColorWatcher: typeof import('./src/components/SideBar/ColorWatcher.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    GridItemsSideBar: typeof import('./src/components/SideBar/GridItemsSideBar.vue')['default']
    MenuNavigationSideBar: typeof import('./src/components/SideBar/MenuNavigationSideBar.vue')['default']
    RootSideBar: typeof import('./src/components/SideBar/RootSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SettingsSideBar: typeof import('./src/components/SideBar/SettingsSideBar.vue')['default']
    SVGWavesHeader: typeof import('./src/components/SVGWavesHeader.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    WavesHeader: typeof import('./src/components/WavesHeader.vue')['default']
    WelcomeHeader: typeof import('./src/components/WelcomeHeader.vue')['default']
  }
}
